# Generated by Django 3.2.4 on 2021-06-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
