# Generated by Django 3.2.4 on 2021-06-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210629_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='MemberVO',
        ),
    ]
